function makeHtml(recipe) {
    const ingredientsHtml = recipe.ingredients.map(i => <li>${i}</li>).join('\n');
    const stepsHtml = (recipe.steps || []).map((s, idx) => <li><strong>Step ${idx + 1}:</strong> ${s}</li>).join('\n');
    const nutrition = recipe.nutrition || {};

    return `
    <!doctype html>
    <html>
    <head>
        <meta charset="utf-8" />
        <title>${recipe.title}</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; color: #333 }
            h1 { color: #2b2b8a }
            .section { margin-bottom: 20px; }
            ul { line-height: 1.6; }
            .nutrition { background: #f8f8f8; padding: 10px; border-radius: 6px; display:inline-block;}
        </style>
    </head>
  <body>
    <h1>${recipe.title}</h1>
    <div class="section">
      <h2>Ingredients</h2>
      <ul>${ingredientsHtml}</ul>
    </div>
    <div class="section">
      <h2>Steps</h2>
      <ol>
        ${(recipe.steps || []).map(s => <li>${s}</li>).join('')}
      </ol>
    </div>
    <div class="section">
      <h2>Nutrition (Estimate)</h2>
      <div class="nutrition">
        <div>Calories: ${nutrition.calories ?? 'N/A'}</div>
        <div>Protein: ${nutrition.protein_g ?? 'N/A'} g</div>
        <div>Fat: ${nutrition.fat_g ?? 'N/A'} g</div>
        <div>Carbs: ${nutrition.carbs_g ?? 'N/A'} g</div>
      </div>
    </div>
    <footer><small>Generated by AI Recipe Generator</small></footer>
  </body>
  </html>
  `;
}

module.exports = { makeHtml };